import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "@/context/AuthContext";
import LayoutContent from "@/app/components/ui/LayoutContent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WODX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}>
        <div className="mx-auto max-w-[375px] min-h-screen bg-[#0a0a0a] relative">
          <AuthProvider>
            <LayoutContent>{children}</LayoutContent>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
